/*
# Seed Products Part 2 (Earbuds, Headphones, Speakers, Gaming, Power, Smart Home, Computer, Drones)

Inserts 12 more products across remaining categories.
*/

INSERT INTO products (category_id, name, slug, description, price, compare_at_price, currency, stock_quantity, sku, image_url, images, specifications, rating, review_count, is_active, is_featured, is_new_arrival, is_on_sale)
VALUES
-- WIRELESS EARBUDS
((SELECT id FROM categories WHERE slug='wireless-earbuds'), 'AirSound Pro 3', 'airsound-pro-3', 'Premium true wireless earbuds with active noise cancellation, spatial audio, and 30-hour total battery with charging case.', 249.00, 279.00, 'USD', 60, 'EB-ASP-3', 'https://images.pexels.com/photos/33797659/pexels-photo-33797659.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '["https://images.pexels.com/photos/33797659/pexels-photo-33797659.jpeg?auto=compress&cs=tinysrgb&h=650&w=940","https://images.pexels.com/photos/3921827/pexels-photo-3921827.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, '{"Type": "True Wireless", "ANC": "Yes (Adaptive)", "Battery": "8h earbuds / 30h with case", "Charging": "USB-C + Wireless", "Bluetooth": "5.3", "Water Resistance": "IPX4", "Audio": "Custom 11mm drivers", "Weight": "5.3g per bud"}'::jsonb, 4.6, 421, true, true, true, true),

((SELECT id FROM categories WHERE slug='wireless-earbuds'), 'BassBuds Mini', 'bassbuds-mini', 'Compact wireless earbuds with deep bass, touch controls, and 20-hour battery. Great value for everyday listening.', 79.00, 99.00, 'USD', 90, 'EB-BBM', 'https://images.pexels.com/photos/3921827/pexels-photo-3921827.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '["https://images.pexels.com/photos/3921827/pexels-photo-3921827.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, '{"Type": "True Wireless", "ANC": "No", "Battery": "6h earbuds / 20h with case", "Charging": "USB-C", "Bluetooth": "5.2", "Water Resistance": "IPX5", "Audio": "10mm dynamic drivers", "Weight": "4.5g per bud"}'::jsonb, 4.2, 189, true, false, false, true),

-- HEADPHONES
((SELECT id FROM categories WHERE slug='headphones'), 'StudioMax Over-Ear ANC', 'studiomax-over-ear-anc', 'Premium over-ear headphones with adaptive noise cancellation, 40-hour battery, and studio-grade sound. Perfect for music production and immersive listening.', 349.00, 399.00, 'USD', 35, 'HP-SMAX-ANC', 'https://images.pexels.com/photos/210927/pexels-photo-210927.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '["https://images.pexels.com/photos/210927/pexels-photo-210927.jpeg?auto=compress&cs=tinysrgb&h=650&w=940","https://images.pexels.com/photos/29407274/pexels-photo-29407274.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, '{"Type": "Over-Ear", "ANC": "Yes (Adaptive Hybrid)", "Battery": "40 hours", "Charging": "USB-C Fast Charge", "Bluetooth": "5.3 + Multipoint", "Drivers": "40mm beryllium", "Weight": "254g", "Latency": "Low Latency Mode"}'::jsonb, 4.8, 267, true, true, false, true),

((SELECT id FROM categories WHERE slug='headphones'), 'GamingHeadset Pro X', 'gamingheadset-pro-x', 'Professional gaming headset with 7.1 surround sound, detachable boom mic, and RGB lighting. Compatible with PC, console, and mobile.', 159.00, 189.00, 'USD', 55, 'HP-GHPX', 'https://images.pexels.com/photos/9742608/pexels-photo-9742608.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '["https://images.pexels.com/photos/9742608/pexels-photo-9742608.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, '{"Type": "Over-Ear Gaming", "Surround": "7.1 Virtual", "Battery": "Wired", "Mic": "Detachable Cardioid Boom", "Drivers": "50mm Neodymium", "Weight": "320g", "RGB": "Yes", "Compatibility": "PC, PS5, Xbox, Switch, Mobile"}'::jsonb, 4.5, 143, true, true, false, true),

-- BLUETOOTH SPEAKS
((SELECT id FROM categories WHERE slug='bluetooth-speakers'), 'SoundBoom Portable', 'soundboom-portable', 'Waterproof portable Bluetooth speaker with 360-degree sound, 24-hour battery, and deep bass. IPX7 rated for pool parties and outdoor adventures.', 129.00, 149.00, 'USD', 70, 'SP-SB-PORT', 'https://images.pexels.com/photos/374110/pexels-photo-374110.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '["https://images.pexels.com/photos/374110/pexels-photo-374110.jpeg?auto=compress&cs=tinysrgb&h=650&w=940","https://images.pexels.com/photos/4917455/pexels-photo-4917455.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, '{"Type": "Portable Bluetooth", "Battery": "24 hours", "Water Resistance": "IPX7", "Bluetooth": "5.3", "Power": "30W", "Drivers": "Dual 40mm + Passive Radiator", "Weight": "540g", "Party Pairing": "Yes (up to 100 speakers)"}'::jsonb, 4.6, 312, true, true, true, true),

((SELECT id FROM categories WHERE slug='bluetooth-speakers'), 'PartySpeaker XL', 'partyspeaker-xl', 'High-power party speaker with LED light show, karaoke mic input, and 12-hour battery. Bring the party anywhere.', 299.00, 349.00, 'USD', 25, 'SP-PS-XL', 'https://images.pexels.com/photos/13465232/pexels-photo-13465232.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '["https://images.pexels.com/photos/13465232/pexels-photo-13465232.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, '{"Type": "Party Speaker", "Battery": "12 hours", "Water Resistance": "IPX5", "Bluetooth": "5.3", "Power": "120W", "Drivers": "8 inch Woofer + 2 Tweeters", "Weight": "5.5kg", "Features": "LED Light Show, Karaoke Mic, FM Radio"}'::jsonb, 4.3, 78, true, false, false, true),

-- GAMING ACCESSORIES
((SELECT id FROM categories WHERE slug='gaming-accessories'), 'RGB Mechanical Keyboard', 'rgb-mechanical-keyboard', 'Hot-swappable mechanical gaming keyboard with per-key RGB, tactile switches, and aluminum frame. USB-C and wireless connectivity.', 139.00, 169.00, 'USD', 50, 'GM-RGB-KB', 'https://images.pexels.com/photos/9020272/pexels-photo-9020272.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '["https://images.pexels.com/photos/9020272/pexels-photo-9020272.jpeg?auto=compress&cs=tinysrgb&h=650&w=940","https://images.pexels.com/photos/5380584/pexels-photo-5380584.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, '{"Type": "Mechanical Gaming", "Switches": "Hot-Swappable Tactile", "Layout": "TKL 87-key", "RGB": "Per-key 16.8M colors", "Connectivity": "USB-C + 2.4GHz + Bluetooth", "Battery": "4000mAh", "Frame": "CNC Aluminum", "Weight": "1.1kg"}'::jsonb, 4.7, 198, true, true, true, true),

((SELECT id FROM categories WHERE slug='gaming-accessories'), 'Precision Gaming Mouse', 'precision-gaming-mouse', 'Ultra-light 58g gaming mouse with 26K DPI optical sensor, optical switches, and 70-hour battery. Built for esports performance.', 89.00, 109.00, 'USD', 65, 'GM-PRECISE-MS', 'https://images.pexels.com/photos/7047612/pexels-photo-7047612.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '["https://images.pexels.com/photos/7047612/pexels-photo-7047612.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, '{"Sensor": "26000 DPI Optical", "Weight": "58g", "Buttons": "6 Optical Switches", "Connectivity": "2.4GHz + USB-C Wired", "Battery": "70 hours", "Polling Rate": "1000Hz", "RGB": "Zone Lighting"}'::jsonb, 4.6, 156, true, false, true, true),

-- CHARGERS & POWER BANKS
((SELECT id FROM categories WHERE slug='chargers-power-banks'), 'PowerCore 20000 PD', 'powercore-20000-pd', '20000mAh power bank with 65W USB-C Power Delivery. Charge laptops, phones, and tablets simultaneously. Fast recharge in 2 hours.', 79.00, 99.00, 'USD', 110, 'PB-PC20K', 'https://images.pexels.com/photos/4072683/pexels-photo-4072683.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '["https://images.pexels.com/photos/4072683/pexels-photo-4072683.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, '{"Capacity": "20000mAh", "Output": "65W USB-C PD + 18W USB-A", "Ports": "1x USB-C, 2x USB-A", "Recharge": "2 hours (65W)", "Weight": "350g", "Display": "LED Battery Indicator", "Protections": "Temp, Short Circuit, Overcharge"}'::jsonb, 4.7, 445, true, true, false, true),

((SELECT id FROM categories WHERE slug='chargers-power-banks'), 'GaN Charger 100W', 'gan-charger-100w', 'Compact 100W GaN charger with 4 ports (2x USB-C, 2x USB-A). Charges laptop, phone, and accessories from one plug.', 59.00, 69.00, 'USD', 95, 'CH-GAN100', 'https://images.pexels.com/photos/37475662/pexels-photo-37475662.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '["https://images.pexels.com/photos/37475662/pexels-photo-37475662.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, '{"Type": "GaN Fast Charger", "Total Power": "100W", "Ports": "2x USB-C PD, 2x USB-A QC", "Input": "100-240V AC", "Size": "60x60x30mm", "Weight": "120g", "Protections": "Overcurrent, Overvoltage, Temperature"}'::jsonb, 4.5, 212, true, false, true, true),

-- SMART HOME
((SELECT id FROM categories WHERE slug='smart-home'), 'SmartHub Mini', 'smarthub-mini', 'Compact smart home hub with built-in Zigbee, Matter, and Wi-Fi. Control all your smart devices from one app. Voice assistant compatible.', 99.00, 129.00, 'USD', 85, 'SH-SH-MINI', 'https://images.pexels.com/photos/22307556/pexels-photo-22307556.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '["https://images.pexels.com/photos/22307556/pexels-photo-22307556.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, '{"Protocols": "Zigbee 3.0, Matter, Wi-Fi 6, Thread", "Power": "USB-C", "Voice Control": "Alexa, Google, Siri", "Size": "85x85x25mm", "Weight": "120g", "App": "iOS + Android", "Automations": "Unlimited rules"}'::jsonb, 4.4, 178, true, false, true, true),

-- COMPUTER ACCESSORIES
((SELECT id FROM categories WHERE slug='computer-accessories'), 'UltraWide Monitor 34', 'ultrawide-monitor-34', '34-inch curved ultrawide monitor with 144Hz refresh rate, 1ms response, and USB-C 90W charging. Perfect for productivity and gaming.', 599.00, 699.00, 'USD', 20, 'CA-UW-34', 'https://images.pexels.com/photos/326512/pexels-photo-326512.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '["https://images.pexels.com/photos/326512/pexels-photo-326512.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, '{"Display": "34 inch Curved Ultrawide", "Resolution": "3440x1440 WQHD", "Refresh Rate": "144Hz", "Response Time": "1ms", "Panel": "VA", "Brightness": "400 nits", "Ports": "USB-C 90W, 2x HDMI, DisplayPort", "Adjustable": "Height, Tilt, Swivel"}'::jsonb, 4.6, 91, true, true, false, true),

-- DRONES & CAMERAS
((SELECT id FROM categories WHERE slug='drones-cameras'), 'Aerial Drone 4K Pro', 'aerial-drone-4k-pro', 'Compact folding drone with 4K HDR camera, 3-axis gimbal, 35-minute flight time, and 10km range. Obstacle avoidance in all directions.', 899.00, 999.00, 'USD', 18, 'DR-AD-4KPRO', 'https://images.pexels.com/photos/1336211/pexels-photo-1336211.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '["https://images.pexels.com/photos/1336211/pexels-photo-1336211.jpeg?auto=compress&cs=tinysrgb&h=650&w=940","https://images.pexels.com/photos/3823555/pexels-photo-3823555.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, '{"Camera": "4K HDR 60fps", "Gimbal": "3-Axis Mechanical", "Flight Time": "35 minutes", "Range": "10km", "Obstacle Avoidance": "Omnidirectional", "Max Speed": "68 km/h", "Weight": "249g", "Video Transmission": "O4 HD"}'::jsonb, 4.8, 134, true, true, true, true)
ON CONFLICT (slug) DO NOTHING;
